### ISSUE TITLE
Jest failes with "Value does not exist in theme['spacing']" when spacing value is used

### ISSUE THREAD

**Issue by guytepper** [Shopify/restyle#71]
I'm using a `spacing` theme value on a `Box` component:

```javascript
import React from 'react';
import { Box, Text } from '../';

function NiceBox() {
  return (
    <Box padding="m">
      <Text>So nice!</Text>
    </Box>
  );
}

export default NiceBox;
```

Inside a Jest test file, I try to render the component using `@testing-library/react-native` (see https://github.com/Shopify/restyle/issues/62#issuecomment-712883700)

```javascript
import React from 'react';
import { render } from '@testing-library/react-native';
import NiceBox from './NiceBox';

test('renders correctly', () => {
  render(<NiceBox />);
});
```

Which throws this error:
```
Value 'm' does not exist in theme['spacing']
```

The spacing value exist in the theme deceleration, and renders correctly (outside Jest).

Any idea why is that? 🥺

**Comment by kulyk** [comment]
@guytepper hi, `restyle` requires the `ThemeProvider` component to wrap the whole application. You pass the `theme` object as the ThemeProvider's prop and it makes the theme available to nested components via React Context. So when you're rendering `<Bod padding="m" />`, the `Box` component tries to get the theme context. But it's not present in your test. Usually, a good practice here is to create your custom `render` wrapper to set up your contexts, e.g.:

```javascript
// Some global test-utils.js file

import React from 'react';
import { ThemeProvider } from '@shopify/restyle';
import { render as rntlRender } from '@testing-library/react-native';

const theme = {
   // some options here
   spacing: {
     s: 4,
     m: 8,
     l: 10,
   },
}

function render(ui, opts) {
    return render(ui, {
           wrapper: ({children}) => (
                  <ThemeProvider theme={theme}>
                     {children}
                  </ThemeProvider>
           )
       },
    )
}

export * from '@testing-library/react-native';
export {render};
```

And then later in your test:

```javascript
// NiceBox.test.jsx

import React from 'react';
import { render } from './test-utils';
import NiceBox from './NiceBox';

test('renders correctly', () => {
  render(<NiceBox />);
});
```

You can use Jest's [moduleDirectory option](https://jestjs.io/docs/en/configuration.html#moduledirectories-arraystring) and [eslint-import-resolver-jest](https://github.com/JoinColony/eslint-import-resolver-jest) to allow absolute imports for `test-utils`, so no matter how deep in your folder structure the component test file is located, you can import it like `import { render } from 'test-utils'`

**Comment by guytepper** [comment]
Hi @kulyk, thanks a lot for the response!

I've tried your solution and got this error: 

```
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.

      at Object.get Dimensions [as Dimensions] (node_modules/react-native/index.js:213:12)
      at node_modules/@shopify/restyle/dist/hooks/useDimensions.js:13:52
      at Object.invokeGuardedCallbackProd (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11308:10)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11499:31)
```

---
On another note, I also had issues with setting the import resolver.
I've set up `eslint-plugin-import`, then installed `eslint-import-resolver-jest` and added `moduleDirectories` to the Jest config - but it was still unable to resolve the module:

```javascript
// src/tests/tests-utils.tsx

import React from 'react';
import { ThemeProvider } from '@shopify/restyle';
import { render as rntlRender } from '@testing-library/react-native';
import theme from '../theme';

function render(ui: React.ReactElement) {
  return rntlRender(ui, {
    wrapper: ({ children }) => <ThemeProvider theme={theme}>{children}</ThemeProvider>,
  });
}

export * from '@testing-library/react-native';
export { render };

```

```javascript
// .eslintrc.js

module.exports = {
  root: true,
  extends: ['@react-native-community', 'plugin:import/errors', 'plugin:import/warnings', 'plugin:import/typescript'],
  settings: {
    'import/resolver': {
      jest: {
        jestConfigFile: './jest.config.js',
      },
    },
  },
};
```

```javascript
// jest.config.js

module.exports = {
  preset: 'react-native',
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  moduleDirectories: ['node_modules', './src/tests'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  transform: {
    '^.+\\.(js)$': '<rootDir>/node_modules/babel-jest',
    '\\.(ts|tsx)$': '<rootDir>/node_modules/ts-jest/preprocessor.js',
  },
  testRegex: '(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$',
  testPathIgnorePatterns: ['\\.snap$', '<rootDir>/node_modules/'],
  cacheDirectory: '.jest/cache',
};

```

```javascript
// test file
import { render } from 'test-utils';
                          ^^^^^^^
Cannot find module 'test-utils' or its corresponding type declarations.ts(2307)
```

What am I missing here? 🤔

**Comment by kulyk** [comment]
Not sure about the `You are trying to import the file` error 🤔

About the `test-utils`, try adding `moduleNameMapper` to your Jest config

```javascript
moduleNameMapper: {
   'tests/(.*)': '<rootDir>/src/tests/$1',
}
```

An then in the test file: `import { render } from 'tests/test-utils'`

**Comment by kulyk** [comment]
@guytepper the `You are trying to `import` a file after the Jest environment has been torn down.` is probably related to #62 but I am not sure

**Comment by guytepper** [comment]
It didn't work 😕

As a temporary solution I mocked restyle's `Box` and `Text` components with React Native's `View` and `Text` components.
Do you think it's a sufficient solution, given my tests are focused mainly on the component's functionality rather than the UI?

**Comment by kulyk** [comment]
In that way, you probably would need to mock almost any component using the restyle theme as each of them will use the `useDimensions` hook. So you can also try to globally mock the `useDimensions` hook, e.g. in your `setupJest` file

**Comment by Chasty** [comment]
> @guytepper hi, `restyle` requires the `ThemeProvider` component to wrap the whole application. You pass the `theme` object as the ThemeProvider's prop and it makes the theme available to nested components via React Context. So when you're rendering `<Bod padding="m" />`, the `Box` component tries to get the theme context. But it's not present in your test.
> 
> Usually, a good practice here is to create your custom `render` wrapper to set up your contexts, e.g.:
> 
> ```js
> // Some global test-utils.js file
> 
> import React from 'react';
> import { ThemeProvider } from '@shopify/restyle';
> import { render as rntlRender } from '@testing-library/react-native';
> 
> const theme = {
>    // some options here
>    spacing: {
>      s: 4,
>      m: 8,
>      l: 10,
>    },
> }
> 
> function render(ui, opts) {
>     return rntlRender(ui, {
>            wrapper: ({children}) => (
>                   <ThemeProvider theme={theme}>
>                      {children}
>                   </ThemeProvider>
>            )
>        },
>     )
> }
> 
> export * from '@testing-library/react-native';
> export {render};
> ```
> 
> And then later in your test:
> 
> ```js
> // NiceBox.test.jsx
> 
> import React from 'react';
> import { render } from './test-utils';
> import NiceBox from './NiceBox';
> 
> test('renders correctly', () => {
>   render(<NiceBox />);
> });
> ```
> 
> You can use Jest's [moduleDirectory option](https://jestjs.io/docs/en/configuration.html#moduledirectories-arraystring) and [eslint-import-resolver-jest](https://github.com/JoinColony/eslint-import-resolver-jest) to allow absolute imports for `test-utils`, so no matter how deep in your folder structure the component test file is located, you can import it like `import { render } from 'test-utils'`
> 
> This is a very common scenario, I guess having a small note on that in the documentation would be very helpful
> I'd be happy to open the PR if it aligns with Shopify's doc vision for this project 🙂

I did that, and I'm getting this.
`TypeError: Cannot read property 'defaults' of undefined

      at func (node_modules/@shopify/restyle/dist/createVariant.js:30:47)
      at node_modules/@shopify/restyle/dist/composeRestyleFunctions.js:32:48
          at Array.reduce (<anonymous>)
      at Object.buildStyle (node_modules/@shopify/restyle/dist/composeRestyleFunctions.js:31:22)
      at Object.useRestyle [as default] (node_modules/@shopify/restyle/dist/hooks/useRestyle.js:38:41)
      at node_modules/@shopify/restyle/dist/createRestyleComponent.js:23:47
      at renderWithHooks (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5552:18)
      at updateForwardRef (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7288:20)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9068:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12649:12)

  console.error
    The above error occurred in the <ForwardRef> component:
        in ForwardRef (created by NiceBox)
        in View (created by View)
        in View (created by ForwardRef)
        in ForwardRef (created by NiceBox)
        in NiceBox
        in Unknown (created by wrapper)
        in wrapper`

**Comment by chj-damon** [comment]
@guytepper I'm facing the same problem you met. Have you solved this?

**Comment by chj-damon** [comment]
> @guytepper the `You are trying to import a file after the Jest environment has been torn down.` is probably related to #62 but I am not sure

any idea how to fix this?

**Comment by chj-damon** [comment]
add `jest.useFakeTimers();` solved my problem.

**Comment by guytepper** [comment]
@chj-damon nice! do you know why the timeout mock helps here? 😅

**Comment by caelinsutch** [comment]
> add `jest.useFakeTimers();` solved my problem.

Where did you put this?

Using:
```

import React from 'react';
import { ThemeProvider } from '@shopify/restyle';
import { render as rntlRender } from '@testing-library/react-native';

const theme = {
   // some options here
   spacing: {
     s: 4,
     m: 8,
     l: 10,
   },
}

function render(ui, opts) {
    return rntlRender(ui, {
           wrapper: ({children}) => (
                  <ThemeProvider theme={theme}>
                     {children}
                  </ThemeProvider>
           )
       },
    )
}

export * from '@testing-library/react-native';
export {render};
```

worked for all my tests. However, when trying to use Storybook snapshot testing, i.e.:
```
// storybook.test.tsx
import initStoryshots from '@storybook/addon-storyshots';
initStoryshots();
```

I got the error.

**Comment by chj-damon** [comment]
@caelinsutch you create a `setup.js` file. and in your `jest.config.js`, 
```code
setupFiles: ['<rootDir>/jest/setup.js'],
```

**Comment by getinnocuous** [comment]
I'm also having this issue, is there any workaround?
